#!/bin/bash

# Skript, mis küsib kasutajalt kuunumbrit ning edastab mis kuuga tegu on. Kui sisestatakse mitte sobiv number, edastab
# veakirje.

# Küsib kuu numbrit

read -p "Sisesta kuu number: " arv

# Otsib listist sobiva vastuse

case $arv in
	1) echo "See on Jaanuar" ;;
	2) echo "See on Veebruar" ;;
	3) echo "See on Märts" ;;
	4) echo "See on Aprill" ;;
	5) echo "See on Mai" ;;
	6) echo "See on Juuni" ;;
	7) echo "See on Juuli" ;;
	8) echo "See on August" ;;
	9) echo "See on September" ;;
	10) echo "See on Oktoober" ;;
	11) echo "See on November" ;;
	12) echo "See on Detsember" ;;
	*) echo "Sisestasite ebasobiliku arvu. Sobilik arvud on vahemikus 1 kuni 12!"
esac

# Skripti lõpp
