#!/bin/bash

# Skript, mis küsib kasutajalt arvu ning vastab, kas tegu on algarvuga või mitte

# Küsib arvu

read -p "Sisesta suvaline arv: " arv

# Uurib, kas tegu on algarvuga või mitte. Algselt vaatab, kas arv on 0 või 1, kui on siis ütleb, et see ei ole algarv,
# kui ei ole liigub edasi ning jagab arvu jagajaga. Kui vastus pole võrdne 0-ga, lisab arvu 1 jagajale ja jagab uuesti
# nii kaua kuni vastus tuleb 0. Seejäral kontrollib, kas saadud jagaja ja arv ise on samad. Kui on siis arv on algarv.
# Kui ei ole siis arv ei ole algarv.

if [ $arv -eq 0 -o $arv -eq 1 ]; then
	echo "$arv ei ole algarv!"
else
	jagaja=2
	jaak=$(($arv % $jagaja))

	while [ $jaak -ne 0 ]
	do
		jagaja=$(($jagaja + 1))
		jaak=$(($arv % $jagaja))
	done

	if [ $arv -eq $jagaja ]; then
		echo "$arv on algarv!"

	else echo "$arv ei ole algarv!"
	fi
fi

# Skripti lõpp
