#!/bin/bash

# Skript küsib kasutaja ees- ja perekonnanime ning tervitab neid.

echo -n "Sisesta oma ees- ja perenimi: "

read  nimi

eesnimi="${nimi% *}"
perenimi="${nimi##* }"

echo "Tere tulemast, $nimi."

echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi."
