#!/bin/bash

# Skript küsib kasutaja ees- ja perekonnanime ning tervitab neid.

echo -n "Sisesta oma ees- ja perenimi: "

read  nimi

eesnimi="${nimi% *}"
perenimi="${nimi##* }"

echo "$eesnimi"
echo "$perenimi"
