#!/bin/bash

# Küsib ainepunktide ja nädalate arvu, kasutab neid, et arvutada EAP

# Ainepunktid ja nädalad
read -p "Sisestage ainepunktide arv: " ainepunktid
read -p "Sisestage nädalate arv: " nadalad

# Arvutab EAP
eap=$(($ainepunktid*26))

# Muudab komakohaliseks
aeg=`echo "scale=1;$eap/$nadalad" | bc`

# Ümardab üles
aeg_ymarda="`echo "($aeg+0.9)/1" | bc`"

# Väljastab
echo $aeg_ymarda
