#!/bin/bash

# Skript bussiekskursjoonide korraldajale abiks

# Küsib mitu reisijat ja kohta on

read -p "Mitu reisijat on grupis? " reisijaid
read -p "Mitu kohta on bussis? " kohti

# Arvutab mitu bussi on täis ning mitu reisijat on maha jäänud

bussid_tais=$((reisijaid / kohti))
maha_jaanud=$((reisijaid % kohti))

# Edastab arvutuste tulemused lause vormis
if test $maha_jaanud -gt 0
then
	bussid_tais2=$(($bussid_tais + 1)) 
	echo "Busse läheb vaja $bussid_tais2, sest muidu jääks $maha_jaanud inimest maha."
else
	echo "Kõik reisijad mahuvah täpselt $bussid_tais bussi peale ära."
fi


