#!/bin/bash

# Skript, mis küsib vanust ning väljastab vastava vanuse kategooria.

# Küsib vanust ning salvestab muutujaks

read -p "Sisestage oma vanus: " vanus

# Otsib sobiva kategooria, kuhu sobib vastavalt sisestatud vanusele.

if test $vanus -gt 0 -a $vanus -lt 11
	then
	echo "Oled laps."

elif test $vanus -ge 11 -a $vanus -lt 18
	then
	echo "Oled nooruk."

elif test $vanus -ge 18 -a $vanus -lt 63
	then
	echo "Oled täiskasvanu."

elif test $vanus -ge 63
	then
	echo "Oled senjoor."

else
	echo "Sisestasite sobimatu arvu."

fi
