#!/bin/bash

# Ümber tehtud paaris/paaritu arvutus, mida kasutatakse ilma skripti arvu
# kirjutamiseta, vaid skripti jooksutates määratud numbriga

if [ $# -ne 1 ]

then
	echo "Palun käivita skript arvuga, mille paarsust/paaritust kontrollida soovite."

else
	arv=$1
	jaak=$(( $arv % 2 ))
	if [ $jaak -eq 0 ]
	then 
		echo "$arv on paaris."
	else
		echo "$arv on paaritu."
	fi
fi

# Skripti lõpp.
