#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Kasutusjuhend: $0 nimedefailinimi paroolidefailinimi"
else
  failinimi1=$1
  failinimi2=$2
  if [ -f $failinimi1 -a -r $failinimi1 -a -f $failinimi2 -a -r $failinimi2 ]; then
    echo "Failid on korras"
    exec 3< "$failinimi2"
    paste -d' ' "$failinimi1" "$failinimi2" | while read -r kasutajanimi parool; do
      if [ -n "$kasutajanimi" ] && [ -n "$parool" ]; then
        useradd "$kasutajanimi" -m -s /bin/bash
        kasu_tulemus_nimi=$?
        echo "$kasutajanimi:$parool" | chpasswd
        kasu_tulemus_parool=$?
        if [ $kasu_tulemus_nimi -eq 0 -a $kasu_tulemus_parool -eq 0 ]; then
          echo "Kasutaja nimega $kasutajanimi ja parooliga $parool on lisatud süsteemi"
          cat /etc/passwd | grep $kasutajanimi
          ls -la /home/$kasutajanimi
        else
          echo "Probleem kasutaja $kasutajanimi lisamisega"
            if [ $kasu_tulemus_nimi -eq 0 ]; then
              echo "Probleem seosneb parooliga. Veakood: $kasu_tulemus_parool"
            else
              if [ $kasu_tulemus_parool -eq 0 ]; then
                echo "Probleem seosneb nimega. Veakood: $kasu_tulemus_nimi"
              else
              echo "Probleem seosneb nii nime kui ka parooliga. Veakoodid: $kasu_tulemus_nimi $kasu_tulemus_parool"
              fi
            fi
        fi
      fi
    done
    exec 3<&-
  else
    if [ -f $failinimi1 -a -r $failinimi1 ]; then
      echo "Probleem failiga $failinimi2"
    else
      if [ -f $failinimi2 -a -r $failinimi2 ]; then
        echo "Probleem failiga $failinimi1"
      else
        echo "Probleem failidega $failinimi1 $failinimi2"
      fi
    fi
  fi
fi
