#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Kasutusjuhend: $0 failinimi1 failinimi2"
else
  failinimi1=$1
  failinimi2=$2
  if [ -f $failinimi1 -a -r $failinimi1 ]; then
    echo "Fail on korras"
    for rida in $(cat $failinimi1)
    do
      kasutajanimi=$(echo "$rida" | cut -f1 -d:)
      sh lisa_kasutaja $kasutajanimi
      echo "$rida" | chpasswd 
    done
  else
    echo "probleem failiga $failinimi"
  fi
fi


if [ $# -ne 1 ]; then
  echo "Kasutusjuhend: $0 kasutajanimi"
else
  kasutajanimi=$1 
  useradd $kasutajanimi -m -s /bin/bash
  kasu_tulemus=$?
  if [ $kasu_tulemus -eq 0 ]; then
    echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi"
    cat /etc/passwd | grep $kasutajanimi
    ls -la /home/$kasutajanimi
  else
    echo "probleem kasutaja $kasutajanimi lisamisega"
    echo "probleemi kood on $kasu_tulemus"
  fi
fi

